# Generated by Django 3.2.9 on 2021-11-25 10:27

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_uploads', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(max_length=15)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('add', models.BooleanField(default=False)),
                ('profile_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_uploads.uploads')),
            ],
            options={
                'db_table': 'auth_employee',
            },
        ),
    ]
