# Generated by Django 3.2.9 on 2021-11-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_alter_employee_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='add',
        ),
    ]
