# Generated by Django 3.2.9 on 2021-11-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_remove_employee_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(default='ddede.jpg', upload_to='profile'),
        ),
    ]
