# Generated by Django 3.2.9 on 2021-11-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_uploads', '0001_initial'),
        ('app_organization', '0002_alter_organization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_uploads.uploads'),
        ),
    ]
